package com.model;

import java.util.List;

/**
 * TCatelog generated by MyEclipse Persistence Tools
 */

public class TCatelog implements java.io.Serializable
{

	private Integer catelogId;
	private String catelogName;
	private Integer userId;
	
	public Integer getCatelogId()
	{
		return catelogId;
	}
	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}
	public String getCatelogName()
	{
		return catelogName;
	}
	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	
}